### ISSUE TITLE
wxgtk2 dependency issue

### ISSUE THREAD

**Issue by u6bkep** [funilrys/aur-urbackup2-client#1]
as per [Antonio Rojas's post on news](https://archlinux.org/news/wxwidgets-32-update-may-need-manual-intervention/), wxgtk is being renamed wxwidgets and dropping gtk2 support. urbackup2-client needs dependencies adjusted.

**Comment by wechsler42** [comment]
Hi there, 
I just run into an error while trying to update my Manjaro box: "could not satisfy dependencies: - removing wxgtk-common breaks dependency 'wxgtk-common' required by wxgtk2". The only dependency which needs wxgtk2 is urbackup2-client on my computer. I would be happy if the dependency issue could be repaired. Thanks in advance for that.

**Comment by syntaxerrormmm** [comment]
Well, removing wxgtk2 and following instructions already find another dependency correctly (as of today on a Manjaro installation, if you chose wxwidgets2 as replacement for wxgtk2); but build phase still breaks with the following error:
```
client/main.cpp: In member function ‘virtual bool MyApp::OnInit()’:
client/main.cpp:354:9: error: duplicate case value
  354 |         case wxLANGUAGE_SPANISH_MODERN:
      |         ^~~~
client/main.cpp:342:9: note: previously used here
  342 |         case wxLANGUAGE_SPANISH:
      |         ^~~~
client/main.cpp:375:9: error: duplicate case value
  375 |         case wxLANGUAGE_CHINESE_TAIWAN:
      |         ^~~~
client/main.cpp:374:9: note: previously used here
  374 |         case wxLANGUAGE_CHINESE_TRADITIONAL:
      |         ^~~~
make[2]: *** [Makefile:4564: client/urbackupclientgui-main.o] Errore 1
```
I don't have sufficient knowledge to understand if this is a simple-to-fix syntax-related issue or much more deep in the sources, unfortunately, so I cannot provide a patch.

**Comment by funilrys** [comment]
Hi everyone, 

can someone test https://github.com/funilrys/aur-urbackup2-client/commit/c3e3f553792c8d4731fa3a93d898eba3cca2d354 and tell me if it solves the issue ? 

Thanks in advance!

Cheers!

**Comment by ThomasK1966** [comment]
Hi, I think I have a good solution for this issue. Now the package depands on the wxwidgets-package from the offical repository (not from AUR). For this solution I have to patch the file client/main.cpp. I have remarked two language-case-statemants with no code in it. Now the gui comes with a modern look. It runs for me on Manjaro unstable.

This was my first work on an issue on github. I hope works for you.

#https://github.com/ThomasK1966/aur-urbackup2-client/commit/141d9133e496ad5a748d8a5d2f60f3e78c2da7fb

**Comment by wechsler42** [comment]
> Hi everyone,
> 
> can someone test [c3e3f55](https://github.com/funilrys/aur-urbackup2-client/commit/c3e3f553792c8d4731fa3a93d898eba3cca2d354) and tell me if it solves the issue ?
> 
> Thanks in advance!
> 
> Cheers!

Hi there,
Thanks for providing a solution suggestion.
I uninstalled the [urbackup2-client](https://github.com/funilrys/aur-urbackup2-client) completely. After that I uninstalled the WXGTK2 package. Then I tried to install urbackup2-client  with this modification:
[delete line] depends=('wxgtk2' 'crypto++' 'zlib')
[add line] depends=('wxgtk2-wxgtk-provides-latest' 'crypto++' 'zlib')
 in the PKGBUILD file.
After the Build process starts I was asked via popup window to choose a provider for wxgtk2. The two options were:
wxgtk2-dev 3.1.7-1 AUR
wxwidgets-gtk2 3.2.0-4 AUR
Unfortunately, whichever option I choose it always leads to a "failed to prepare transaction" error.

**Comment by wechsler42** [comment]
> Hi, I think I have a good solution for this issue. Now the package depands on the wxwidgets-package from the offical repository (not from AUR). For this solution I have to patch the file client/main.cpp. I have remarked two language-case-statemants with no code in it. Now the gui comes with a modern look. It runs for me on Manjaro unstable.
> 
> This was my first work on an issue on github. I hope works for you.
> 
> #[ThomasK1966@141d913](https://github.com/ThomasK1966/aur-urbackup2-client/commit/141d9133e496ad5a748d8a5d2f60f3e78c2da7fb)

Hi there,
Thanks for providing a solution suggestion.
I uninstalled the [urbackup2-client](https://github.com/funilrys/aur-urbackup2-client) completely. After that I uninstalled the WXGTK2 package. Then I tried to install urbackup2-client with this modification:
[delete line] depends=('wxgtk2' 'crypto++' 'zlib')
[add line] depends=('wxwidgets' 'crypto++' 'zlib')
in the PKGBUILD file.
After that the Build process started successfully. Unfortunately it ended with the two language case statement errors you already mentioned. So I would need the fixes you suggested but I do not know how to add the patch file "double_language.patch" in the Pamac GUI.

**Comment by ThomasK1966** [comment]
> > Hi, I think I have a good solution for this issue. Now the package depands on the wxwidgets-package from the offical repository (not from AUR). For this solution I have to patch the file client/main.cpp. I have remarked two language-case-statemants with no code in it. Now the gui comes with a modern look. It runs for me on Manjaro unstable.
> > This was my first work on an issue on github. I hope works for you.
> > #[ThomasK1966@141d913](https://github.com/ThomasK1966/aur-urbackup2-client/commit/141d9133e496ad5a748d8a5d2f60f3e78c2da7fb)
> 
> Hi there, Thanks for providing a solution suggestion. I uninstalled the [urbackup2-client](https://github.com/funilrys/aur-urbackup2-client) completely. After that I uninstalled the WXGTK2 package. Then I tried to install urbackup2-client with this modification: [delete line] depends=('wxgtk2' 'crypto++' 'zlib') [add line] depends=('wxwidgets' 'crypto++' 'zlib') in the PKGBUILD file. After that the Build process started successfully. Unfortunately it ended with the two language case statement errors you already mentioned. So I would need the fixes you suggested but I do not know how to add the patch file "double_language.patch" in the Pamac GUI.

Hi, now I have merged the Patch in my fork of this repository. I think you could  clone my repository and then with makepg compile and create a package.

First create directory, change in this directory. Then

git clone https://github.com/ThomasK1966/aur-urbackup2-client.git
makepkg 

I can‘t test it right now. So, I hope it runs for you.

Greetings Thomas.

**Comment by syntaxerrormmm** [comment]
The patched version provided by @ThomasK1966 compiles fine and runs equally fine. I'm doing an incremental file backup now from Manjaro. Not tried the GUI yet, I really don't need it; but the no-gui package in AUR doesn't work either.

**Comment by funilrys** [comment]
@ThomasK1966, can you please submit a PR ! The credit goes to you!

**Comment by funilrys** [comment]
Thanks @ThomasK1966 , let's test it live!
